PREFIX ex: <http://example.org/wifi#>
SELECT DISTINCT ?proveedor
WHERE {
  ?punto a ex:PuntoDeAccesoWiFi ;
         ex:proveedor ?proveedor ;
         ex:ciudad ?ciudad .
  FILTER (lcase(str(?ciudad)) = lcase("$CIUDAD"))
}
