PREFIX nyc: <http://example.org/nyc_wifi_nyc_public.owl#>

SELECT ?borough (COUNT(?punto) AS ?cantidad)
WHERE {
  ?punto a nyc:Location ;
         nyc:borough ?borough .
}
GROUP BY ?borough
ORDER BY DESC(?cantidad)
LIMIT 5