PREFIX nyc: <http://example.org/nyc_wifi_nyc_public.owl#>

SELECT ?ssid ?lat ?long
WHERE {
  ?wifi a nyc:WifiNetwork ;
        nyc:ssid ?ssid ;
        nyc:hasLocation ?loc ;
        nyc:hasProvider ?prov .
  ?loc nyc:latitude ?lat ;
       nyc:longitude ?long .
  FILTER CONTAINS(lcase(str(?ssid)), "active")
}

