PREFIX ex: <http://example.org/wifi#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT ?ssid ?lat ?long ?estado ?proveedor
WHERE {
  ?punto a ex:PuntoDeAccesoWiFi ;
         ex:nombreSSID ?ssid ;
         ex:estado ?estado ;
         ex:esOperadoPor ?proveedor ;
         geo:lat ?lat ;
         geo:long ?long .
  FILTER CONTAINS(lcase(str(?proveedor)), "gobierno")
}

