PREFIX ex: <http://example.org/wifi#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT ?ssid ?lat ?long ?estado
WHERE {
  ?punto a ex:PuntoDeAccesoWiFi ;
         ex:nombreSSID ?ssid ;
         ex:estado ?estado ;
         geo:lat ?lat ;
         geo:long ?long .
}

