PREFIX ex: <http://www.semanticweb.org/ontowifi#>

SELECT ?punto ?lat ?lon ?direccion
WHERE {
  ?punto a ex:PuntoDeAccesoWiFi ;
         ex:ciudad "New York" ;
         ex:latitud ?lat ;
         ex:longitud ?lon ;
         ex:direccion ?direccion .
}