PREFIX ex: <http://example.org/wifi#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT ?ssid ?lat ?long ?estado ?seguridad
WHERE {
  ?punto a ex:PuntoDeAccesoWiFi ;
         ex:nombreSSID ?ssid ;
         ex:estado ?estado ;
         ex:usaSeguridad ?seguridad ;
         geo:lat ?lat ;
         geo:long ?long .
  FILTER(lcase(str(?seguridad)) = "abierto")
}
