PREFIX ex: <http://example.org/wifi#>

SELECT ?punto ?proveedor
WHERE {
  ?punto a ex:PuntoDeAccesoWiFi ;
         ex:ciudad "Buenos Aires" ;
         ex:proveedor "Gobierno_BA" ;
         ex:proveedor ?proveedor .
}