PREFIX wifi: <http://example.org/wifi#>

SELECT ?barrio (COUNT(?punto) AS ?cantidad)
WHERE {
  ?punto a wifi:PuntoDeAccesoWiFi ;
         wifi:barrio ?barrio .
}
GROUP BY ?barrio
ORDER BY DESC(?cantidad)
LIMIT 5