PREFIX ex: <http://example.org/wifi#>

SELECT ?punto ?proveedor
WHERE {
  ?punto a ex:PuntoDeAccesoWiFi ;
         ex:ciudad "New York" ;
         ex:proveedor "Gobierno_NY" ;
         ex:proveedor ?proveedor .
}