PREFIX wifi: <http://example.org/wifi#>
SELECT ?id ?lat ?lon ?city
WHERE {
    ?wifi a wifi:WiFi ;
          wifi:lat ?lat ;
          wifi:lon ?lon ;
          wifi:city ?city ;
          wifi:isOpen true .
    BIND(STRAFTER(STR(?wifi), "#") AS ?id)
}
