PREFIX ex: <http://example.org/wifi#Seguridad
>
SELECT ?ssid ?lat ?lon ?ciudad
WHERE {
    ?wifi a ex:WiFi.
    ?wifi ex:ssid ?ssid.
    ?wifi ex:latitud ?lat.
    ?wifi ex:longitud ?lon.
    ?wifi ex:ciudad ?ciudad.
    ?wifi ex:esSeguro true.
}