PREFIX wifi: <http://example.org/wifi#>
SELECT ?provider ?lat ?lon ?city
WHERE {
    ?wifi a wifi:WiFi ;
        wifi:provider ?provider ;
        wifi:lat ?lat ;
        wifi:lon ?lon ;
        wifi:city ?city .
    FILTER(?city = "Buenos Aires" || ?city = "New York")
}