PREFIX wifi: <http://example.org/wifi#>
SELECT ?id ?lat ?lon ?provider ?city
WHERE {
    ?wifi a wifi:WiFi ;
          wifi:lat ?lat ;
          wifi:lon ?lon ;
          wifi:provider ?provider ;
          wifi:city ?city .
    FILTER(?city = "Buenos Aires" || ?city = "New York")
    BIND(STRAFTER(STR(?wifi), "#") AS ?id)
}
